# This is a basic workflow to help you get started with Actions

name: Unit test

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # Build ubuntu
      - name: install build tool (ubuntu)
        run: |
              sudo apt-get update
              sudo apt-get install \
                  curl build-essential make gcc g++ python3
              sudo apt-get install clang-11 --install-suggests
      
      # Install python package by poetry
      - name: Install python package by poetry
        run: |        
              curl -sSL https://install.python-poetry.org | python3 -
              poetry install
              
      # Runs test script
      - name: Run Simu_test.py script in test/
        run: |
              poetry run make test
